server:
  port: 8081
  servlet:
    context-path: /mmbao
spring:
  application:
    name: mmbao_web_api
  datasource:
    url: jdbc:mysql://192.168.0.158:3306/mmbao?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 100
  redis:
    password: javasm
    host: 192.168.0.158
    port: 6379
  mail:
    protocol: smtp
    host: smtp.163.com
    port: 465
    username: 19937782588@163.com
    password: SYRZLRNOCSLFQJKA
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  task:
    execution:
      pool:
        core-size: 5
        max-size: 20
        queue-capacity: 1000
  servlet:
    multipart:
      max-file-size: 100MB
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
